# Generated by Django 5.1.5 on 2025-04-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=255)),
                ('urgency_level', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('contact_number', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proof', models.FileField(upload_to='proofs/')),
                ('anonymous', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
