# Generated by Django 5.1.5 on 2025-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeCityHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencies',
            name='location',
        ),
        migrations.AddField(
            model_name='emergencies',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencies',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
