# Generated by Django 5.1.5 on 2025-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeCityHub', '0002_remove_emergencies_location_emergencies_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencies',
            old_name='date_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='emergencies',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='emergencies',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='emergencies',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencies',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencies',
            name='incident_type',
            field=models.CharField(choices=[('crime', 'Crime'), ('accident', 'Accident'), ('civic', 'Civic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencies',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='emergencies',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
