# Generated by Django 5.2 on 2025-04-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeCityHub', '0004_emergencies_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emergencies',
        ),
    ]
